### ISSUE TITLE
Building from source fails

### ISSUE THREAD

**Issue by alexmyczko** [Omnibus-Type/Saira#9]
I was trying to build from source with:

`fontmake -g Saira.glyphs -o otf`

and I'd get this error:

```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "Saira.glyphs" file into <GSFont>
WARNING:glyphsLib.builder.axes:Instance user-space location (200) redefined by 'ExtraLight'
WARNING:glyphsLib.builder.axes:Instance user-space location (300) redefined by 'Light'
WARNING:glyphsLib.builder.axes:Instance user-space location (400) redefined by 'Regular'
WARNING:glyphsLib.builder.axes:Instance user-space location (500) redefined by 'Medium'
WARNING:glyphsLib.builder.axes:Instance user-space location (600) redefined by 'SemiBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (700) redefined by 'Bold'
WARNING:glyphsLib.builder.axes:Instance user-space location (800) redefined by 'ExtraBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (900) redefined by 'Black'
WARNING:glyphsLib.builder.axes:Instance user-space location (200) redefined by 'ExtraLight'
WARNING:glyphsLib.builder.axes:Instance user-space location (400) redefined by 'Regular'
WARNING:glyphsLib.builder.axes:Instance user-space location (500) redefined by 'Medium'
WARNING:glyphsLib.builder.axes:Instance user-space location (600) redefined by 'SemiBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (700) redefined by 'Bold'
WARNING:glyphsLib.builder.axes:Instance user-space location (800) redefined by 'ExtraBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (900) redefined by 'Black'
WARNING:glyphsLib.builder.axes:Instance user-space location (200) redefined by 'ExtraLight'
WARNING:glyphsLib.builder.axes:Instance user-space location (300) redefined by 'Light'
WARNING:glyphsLib.builder.axes:Instance user-space location (400) redefined by 'Regular'
WARNING:glyphsLib.builder.axes:Instance user-space location (500) redefined by 'Medium'
WARNING:glyphsLib.builder.axes:Instance user-space location (600) redefined by 'SemiBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (700) redefined by 'Bold'
WARNING:glyphsLib.builder.axes:Instance user-space location (800) redefined by 'ExtraBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (900) redefined by 'Black'
WARNING:glyphsLib.builder.axes:Instance user-space location (100) redefined by 'ExtraLight'
WARNING:glyphsLib.builder.axes:Instance user-space location (100) redefined by 'Light'
WARNING:glyphsLib.builder.axes:Instance user-space location (100) redefined by 'Regular'
WARNING:glyphsLib.builder.axes:Instance user-space location (100) redefined by 'Medium'
WARNING:glyphsLib.builder.axes:Instance user-space location (100) redefined by 'SemiBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (100) redefined by 'Bold'
WARNING:glyphsLib.builder.axes:Instance user-space location (100) redefined by 'ExtraBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (100) redefined by 'Black'
WARNING:glyphsLib.builder.axes:Instance user-space location (87.5) redefined by 'ExtraLight'
WARNING:glyphsLib.builder.axes:Instance user-space location (87.5) redefined by 'Light'
WARNING:glyphsLib.builder.axes:Instance user-space location (87.5) redefined by 'Regular'
WARNING:glyphsLib.builder.axes:Instance user-space location (87.5) redefined by 'Medium'
WARNING:glyphsLib.builder.axes:Instance user-space location (87.5) redefined by 'SemiBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (87.5) redefined by 'Bold'
WARNING:glyphsLib.builder.axes:Instance user-space location (87.5) redefined by 'ExtraBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (87.5) redefined by 'Black'
WARNING:glyphsLib.builder.axes:Instance user-space location (75) redefined by 'ExtraLight'
WARNING:glyphsLib.builder.axes:Instance user-space location (75) redefined by 'Light'
WARNING:glyphsLib.builder.axes:Instance user-space location (75) redefined by 'Regular'
WARNING:glyphsLib.builder.axes:Instance user-space location (75) redefined by 'Medium'
WARNING:glyphsLib.builder.axes:Instance user-space location (75) redefined by 'SemiBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (75) redefined by 'Bold'
WARNING:glyphsLib.builder.axes:Instance user-space location (75) redefined by 'ExtraBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (75) redefined by 'Black'
WARNING:glyphsLib.builder.axes:Instance user-space location (62.5) redefined by 'ExtraLight'
WARNING:glyphsLib.builder.axes:Instance user-space location (62.5) redefined by 'Light'
WARNING:glyphsLib.builder.axes:Instance user-space location (62.5) redefined by 'Regular'
WARNING:glyphsLib.builder.axes:Instance user-space location (62.5) redefined by 'Medium'
WARNING:glyphsLib.builder.axes:Instance user-space location (62.5) redefined by 'SemiBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (62.5) redefined by 'Bold'
WARNING:glyphsLib.builder.axes:Instance user-space location (62.5) redefined by 'ExtraBold'
WARNING:glyphsLib.builder.axes:Instance user-space location (62.5) redefined by 'Black'
Traceback (most recent call last):
  File "/usr/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==2.0.1', 'console_scripts', 'fontmake')()
  File "/usr/lib/python3/dist-packages/fontmake/__main__.py", line 405, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/lib/python3/dist-packages/fontmake/font_project.py", line 647, in run_from_glyphs
    write_skipexportglyphs=write_skipexportglyphs,
  File "/usr/lib/python3/dist-packages/fontTools/misc/loggingTools.py", line 374, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3/dist-packages/fontmake/font_project.py", line 151, in build_master_ufos
    write_skipexportglyphs=write_skipexportglyphs,
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/__init__.py", line 112, in to_designspace
    return builder.designspace
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/builders.py", line 260, in designspace
    self.to_designspace_sources()
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/sources.py", line 36, in to_designspace_sources
    _to_designspace_source_layer(self)
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/sources.py", line 168, in _to_designspace_source_layer
    ].split(",")
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/sources.py", line 166, in <listcomp>
    for c in layer_name[
ValueError: invalid literal for int() with base 10: ' 341 off'
```

Saira-Italic.glyphs works.

**Comment by medicalwei** [comment]
It seems to be a comma in some layer names, which glyphsLib cannot parse correctly.  I think this is probably a bug in glyphsLib if there's no spec violation.
